ass=("Question one")
print(ass)
name=("usman mahmud")
print(name)
name=("mathematic")
print(name)
aaa=("Question two")
print(aaa)
scare=("boo")
print(scare)
aa=("Question three")
print(aa)
aa=(7)
zs=(5)
print(aa+zs)
aa=("Question four")
print(aa)
outcome=(12/0.5)
print(outcome)
aa=("Questionfive")
print(aa)
aa=(22+5)
print(aa)
aa=("Question six")
print(aa)
aa=("modulu %")
print(aa)
aa=("Question seven")
print(aa)
aa=(2*4*4+2)
print(aa)